Home/urls.py
from django.urls import path
from. import views
app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

Post/urls.py
from django.urls import path, include
from . import views

app_name = 'post'

urlpatterns = [
    path('details/<slug:slug>/', views.post_details, name='details'),
    path('add/<int:profile_id>/', views.add_post, name='add_post'),
    path('edit/<int:profile_id>/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:profile_id>/<int:post_id>/', views.delete_post, name='delete_post'),
    path('', include('Like.urls', namespace='like')),
]

SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Home.urls', namespace='home')),
    path('accounts/', include('Accounts.urls', namespace='accounts')),
    path('post/', include('Post.urls', namespace='post')),
    path('comment/', include('Comments.urls', namespace='comment')),
    path('admin/', admin.site.urls),
]

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render
from Post.models import Post


def home(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'home/home.html', context=context)

Home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2><span>Template License</span></h2>
    {% for post in posts %}
            <div class="clr"></div>
            <p class="post-data"><span class="date">{{ post.created }}</span> &nbsp;|&nbsp; Posted by <a href="#">{{ post.user|capfirst }}</a> &nbsp;|&nbsp; Filed under <a href="#">templates</a>, <a href="#">internet</a></p>
            <img src="{% static "images/images_1.jpg" %}" width="613" height="193" alt="" />
            <p>{{ post.text }}</p>
            {%  with comments=comments.all.count %}
            <p class="spec"><a href="#" class="com fr">Comment{{ comments|pluralize }}({{ comments }})</a> <a href="{% url 'post:details' post.slug %}" class="rm fl">Read more</a></p>
            {%  endwith %}
    <div class="clr"></div>
    {% endfor %}
{% endblock %}