Home/urls.py
from django.urls import path
from. import views
app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

Post/urls.py
from django.urls import path, include
from . import views

app_name = 'post'

urlpatterns = [
    path('details/<slug:slug>/', views.post_details, name='details'),
    path('add/<int:profile_id>/', views.add_post, name='add_post'),
    path('edit/<int:profile_id>/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:profile_id>/<int:post_id>/', views.delete_post, name='delete_post'),
    path('', include('Like.urls', namespace='like')),
]

Profile/urls.py
from django.urls import path, include
from . import views


app_name = 'profile'

urlpatterns = [
    path('<int:profile_id>/', views.user_profile, name='user_profile'),
    path('edit/<int:profile_id>/', views.edit_profile, name='edit_profile'),
    path('', include('Follow.urls', namespace='follow')),
]

SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Home.urls', namespace='home')),
    path('accounts/', include('Accounts.urls', namespace='accounts')),
    path('post/', include('Post.urls', namespace='post')),
    path('comment/', include('Comments.urls', namespace='comment')),
    path('admin/', admin.site.urls),
]

Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=200, default='Write Short About You')
    phone = models.PositiveIntegerField(null=True, blank=True)
    follower = models.ManyToManyField(User, related_name='follower', blank=True)
    following = models.ManyToManyField(User, related_name='following', blank=True)

    def __str__(self):
        return self.user.username

    @receiver(signal=post_save, sender=User)
    def save_profile(sender, **kwargs):
        if kwargs['created']:
            user_profile = Profile(user=kwargs['instance'])
            user_profile.save()

Profile/forms.py
from django import forms
from .models import User, Profile


class EditProfileForm(forms.ModelForm):
    username = forms.CharField(max_length=15, min_length=4)
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=30)

    class Meta:
        model = Profile
        fields = ('bio', 'phone',)

Profile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Profile
from .forms import EditProfileForm
from Post.forms import AddPostForm
from Post.models import Post
from django.contrib.auth.decorators import login_required
from Follow.models import Follow


@login_required
def user_profile(request, profile_id):
    profile = get_object_or_404(Profile, pk=profile_id)
    posts = Post.objects.filter(user=request.user)
    relation = Follow.objects.filter(follower=request.user, following=profile, is_following=True)
    form = AddPostForm()
    context = {'profile': profile, 'form': form, 'posts': posts, 'relation': relation}
    return render(request, 'profile/profile.html', context=context)


@login_required
def edit_profile(request, profile_id):
    if request.user.id == profile_id:
        user_edit = get_object_or_404(Profile, pk=profile_id)
        if request.method == 'POST':
            form = EditProfileForm(request.POST, instance=user_edit)
            if form.is_valid():
                form.save()
                user_edit.user.username = form.cleaned_data['username']
                user_edit.user.first_name = form.cleaned_data['first_name']
                user_edit.user.last_name = form.cleaned_data['last_name']
                user_edit.user.email = form.cleaned_data['email']
                user_edit.user.save()
                messages.success(request, 'Your Profile Edited Successfully', 'success')
                return redirect('accounts:profile:user_profile', profile_id)
        else:
            form = EditProfileForm(instance=user_edit, initial={
                'email': user_edit.user.email,
                'first_name': user_edit.user.first_name,
                'last_name': user_edit.user.last_name,
                'username': user_edit.user.username,
            })
        return render(request, 'profile/edit_profile.html', {'form': form})

Profile/templates/profile/edit_profile.html
{% extends 'base.html' %}

{% block content %}
    <form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit Changes" style="background-color: #97c950">
    </form>
{% endblock %}

Profile/templates/profile/profile.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

<nav class="navbar navbar-light bg-white">
        <a href="{% url 'home:home' %}" class="navbar-brand">Home</a>

        <form class="form-inline">
            <div class="input-group">
                <input type="text" class="form-control" aria-label="Recipient's username" aria-describedby="button-addon2">
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="button" id="button-addon2">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </nav>


    <div class="container-fluid gedf-wrapper">
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <div class="h5">@{{ profile.user }}</div>
                        <div class="h7 text-muted">{{ profile.user.get_full_name }}</div>
                        <div class="h7">{{ profile.bio }},
                            etc.
                        </div>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div class="h6 text-muted">Followers</div>
                            <div class="h5">5.2342</div>
                        </li>
                        <li class="list-group-item">
                            <div class="h6 text-muted">Following</div>
                            <div class="h5">6758</div>
                        </li>
                        <li class="list-group-item">Vestibulum at eros</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 gedf-main">

                <!--- \\\\\\\Post-->
                {% if request.user.pk == profile.user.pk %}
                <div class="card gedf-card">
                    <div class="card-header">
                        <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make
                                    a publication</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>
                            </li>
                        </ul>
                    </div>
                    <div class="card-body">
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                                <div class="form-group">
                                    <label class="sr-only" for="message">post</label>
                                    <form method="post" action="{% url 'post:add_post' profile.pk %}">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input type="submit" value="Share" class="btn btn-primary">
                                    </form>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                                <div class="form-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="customFile">
                                        <label class="custom-file-label" for="customFile">Upload image</label>
                                    </div>
                                </div>
                                <div class="py-4"></div>
                            </div>
                        </div>
                        <div class="btn-toolbar justify-content-between">
                            <div class="btn-group">

                            </div>
                            <div class="btn-group">
                                <button id="btnGroupDrop1" type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="fa fa-globe"></i>
                                </button>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                                    <a class="dropdown-item" href="#"><i class="fa fa-globe"></i> Public</a>
                                    <a class="dropdown-item" href="#"><i class="fa fa-users"></i> Friends</a>
                                    <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Just me</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- Post /////-->

                <!--- \\\\\\\Post-->
                {% for post in posts %}
                <div class="card gedf-card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">
                                    <img class="rounded-circle" width="45" src="https://picsum.photos/50/50" alt="">
                                </div>
                                <div class="ml-2">
                                    <div class="h5 m-0">@{{ profile.user }}</div>
                                    <div class="h7 text-muted">{{ post.text|slice:"0:3" }}</div>
                                </div>
                            </div>
                            <div>
                                <div class="dropdown">
                                    <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-ellipsis-h"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                        <div class="h6 dropdown-header">Configuration</div>
                                        <a class="dropdown-item" href="#">Save</a>
                                        <a class="dropdown-item" href="#">Hide</a>
                                        <a class="dropdown-item" href="#">Report</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="card-body">
                        <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>{{ post.created.date }}</div>
                        <a class="card-link" href="#">
                            <h5 class="card-title">Title</h5>
                        </a>

                        <p class="card-text">
                            {{ post.text }}
                        </p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
                        <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
                        <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
                        {% if request.user.id == profile.pk %}
                        <a href="{% url 'post:edit_post' profile.pk post.pk %}" class="card-link"><i class="fa fa-mail-forward"></i> Edit</a>
                        <a href="{% url 'post:delete_post' profile.pk post.pk %}" class="card-link"><i class="fa fa-mail-forward"></i> Delete</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                <!-- Post /////-->


            </div>
            <div class="col-md-3">
                <div class="card gedf-card">
                    <div class="card-body">
                         {% if request.user.id == profile.pk %}
                        <h5 class="card-title">Edit Profile</h5>
                        <a href="{% url 'accounts:profile:edit_profile' profile.pk %}" class="card-link">Enter</a>
                        {% endif %}
                    </div>
                </div>
                <div class="card gedf-card">
                        <div class="card-body">
                            <h5 class="card-title">Follow Part</h5>
                        {% if request.user.id != profile.pk %}
                            {% if relation.exists %}
                                <a href="{% url 'accounts:profile:follow:unfollow' request.user.pk profile.pk %}" class="card-link">UnFollow</a>
                            {% else %}
                                <a href="{% url 'accounts:profile:follow:follow' request.user.pk profile.pk %}" class="card-link">Follow</a>
                            {% endif %}
                        {% endif %}
                            <a href="#" class="card-link">Another link</a>
                        </div>
                    </div>
            </div>
        </div>
    </div>