Accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('profile/', include('Profile.urls', namespace='profile')),
    path('phone/', include('Phone.urls', namespace='phone_login')),
]

Home/urls.py
from django.urls import path
from. import views
app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Home.urls', namespace='home')),
    path('accounts/', include('Accounts.urls', namespace='accounts')),
    path('post/', include('Post.urls', namespace='post')),
    path('comment/', include('Comments.urls', namespace='comment')),
    path('admin/', admin.site.urls),
]

templates/include/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/include/navbar.html
<div class="menu_nav">
        <ul>
          <li class="active"><a href="{% url 'home:home' %}">Home</a></li>
          {% if request.user.is_authenticated %}
              <li><a href="{% url 'accounts:profile:user_profile' request.user.id %}">Profile</a></li>
              <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
              <li><a href="{% url 'accounts:login' %}">Sign In</a></li>
              <li><a href="{% url 'accounts:register' %}">Sign Up</a></li>
          {% endif %}
        </ul>
        <div class="clr"></div>
</div>