Comments/urls.py
from django.urls import path
from Comments import views

app_name = 'comment'

urlpatterns = [
    path('add_reply/<int:post_id>/<int:cm_id>/', views.add_reply, name='add_reply'),
]

Home/urls.py
from django.urls import path
from. import views
app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

Post/urls.py
from django.urls import path, include
from . import views

app_name = 'post'

urlpatterns = [
    path('details/<slug:slug>/', views.post_details, name='details'),
    path('add/<int:profile_id>/', views.add_post, name='add_post'),
    path('edit/<int:profile_id>/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:profile_id>/<int:post_id>/', views.delete_post, name='delete_post'),
    path('', include('Like.urls', namespace='like')),
]

SocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Home.urls', namespace='home')),
    path('accounts/', include('Accounts.urls', namespace='accounts')),
    path('post/', include('Post.urls', namespace='post')),
    path('comment/', include('Comments.urls', namespace='comment')),
    path('admin/', admin.site.urls),
]

Post/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    text = models.TextField(max_length=1000)
    slug = models.SlugField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.text[:10]}'

Post/forms.py
from django import forms
from .models import Post


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text',)
        labels = {
            'text': '',
        }
        widgets = {
            'text': forms.TextInput(
                attrs={"class": "form-control", "id": "message", "rows": "3", "placeholder": "What Are You Thinking?"}
            )}


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text',)
        labels = {
            'text': '',
        }
        widgets = {
            'text': forms.TextInput(
                attrs={"class": "form-control", "id": "message", "rows": "3", }
            )}

Post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Post
from Comments.models import Comment
from .forms import AddPostForm, EditPostForm
from Comments.forms import AddCommentForm, AddReplyForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from Like.models import Like


@login_required
def post_details(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = Comment.objects.filter(post=post, is_reply=False)
    liked = Like.objects.filter(user=request.user, post=post, is_liked=True)
    reply = AddReplyForm()
    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.save()
            messages.success(request, 'Added The Comment', 'success')
    else:
        form = AddCommentForm
    return render(request, 'post/details.html', {'post': post, 'comments': comments,
                                                 'form': form, 'reply': reply, 'liked': liked,
                                                 })


@login_required
def add_post(request, profile_id):
    if request.user.id == profile_id:
        if request.method == 'POST':
            form = AddPostForm(request.POST)
            if form.is_valid():
                new_post = form.save(commit=False)
                new_post.user = request.user
                new_post.slug = slugify(form.cleaned_data['text'][:15])
                new_post.save()
                messages.success(request, 'Post Is Added', 'success')
                return redirect('accounts:profile:user_profile', profile_id)


@login_required
def edit_post(request, profile_id, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user.id == profile_id:
        if request.method == 'POST':
            form = EditPostForm(request.POST, instance=post)
            if form.is_valid():
                ed_post = form.save(commit=False)
                ed_post.user = request.user
                ed_post.slug = slugify(form.cleaned_data['text'][:15])
                ed_post.save()
                messages.success(request, 'Post Is Changed', 'success')
                return redirect('accounts:profile:user_profile', profile_id)
        else:
            form = EditPostForm(instance=post)
        return render(request, 'post/edit_post.html', {'form': form})


@login_required
def delete_post(request, profile_id, post_id):
    if request.user.id == profile_id:
        Post.objects.filter(pk=post_id).delete()
        messages.success(request, 'Your Post Is Deleted Successfully', 'success')
        return redirect('accounts:profile:user_profile', profile_id)
    else:
        return redirect('home:home')

Post/templates/post/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h2><span>Template License</span></h2>
            <div class="clr"></div>
            <p class="post-data"><span class="date">March 16, 2018</span> &nbsp;|&nbsp; Posted by <a href="#">Owner</a> &nbsp;|&nbsp; Filed under <a href="#">templates</a>, <a href="#">internet</a></p>
            <p>{{ post.text }}</p>

    {%  with comments=comments.all.count %}
            <p class="spec"><a href="#" class="com fr">Comment{{ comments|pluralize }}({{ comments }})</a></p>
    {%  endwith %}
    <div class="clr"></div>

    {% if liked %}
        <h3><a href="{% url 'post:like:post_unlike' post.pk %}" style="background-color: brown">Unlike</a></h3>
    {% else %}
        <h3><a href="{% url 'post:like:post_like' post.pk %}" style="background-color: brown">Like</a></h3>
    {% endif %}


    <hr>
    <h3 style="color: #97c950">Write Your Comment:</h3>
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" style="background-color: cornflowerblue">
    </form>
    <br>

   {% for cm in comments %}
       <h3>{{ cm.user|capfirst }}</h3>
       <p>{{ cm.text }}</p>

       {% for reply in cm.reply.all %}
           <h3 style="text-align: right">{{ reply.user }}</h3>
           <p style="text-align: right">{{ reply.text }}</p>
       {% endfor %}

       <form action="{% url 'comment:add_reply' post.pk cm.pk %}" method="post" style="text-align: right">
           {% csrf_token %}
           {{ reply.as_p }}
       <input type="submit" value="Add A Reply" style="background-color: blueviolet; text-align: right">
       </form>
       <hr>
   {% endfor %}


{% endblock %}

Post/templates/post/edit_post.html
{% extends 'base.html' %}

{% block content %}
    <form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit Changes" style="background-color: #78bbe6">
    </form>
{% endblock %}